"""The `relay` CLI.

Project-centric like git: `relay up <folder>` starts (auto-initializing on
first run); every other command finds the project by walking up from the
current directory. --swarm remains as an explicit override everywhere.
"""

from __future__ import annotations

import json
import subprocess as sp
from pathlib import Path

import typer
from rich.console import Console
from rich.table import Table

from relay import __version__
from relay.bus import dlq as dlq_mod
from relay.bus.client import get_client
from relay.bus.keys import ledger_key, presence_key
from relay.cli.context import NoProjectError, resolve_swarm, swarm_name
from relay.contract import ContractValidator, load_contract
from relay.contract.codegen import write_artifacts
from relay.ledger.audit import audit_ledger
from relay.ledger.export import export_jsonl

app = typer.Typer(no_args_is_help=True, help="Relay Agentic Framework")
contract_app = typer.Typer(no_args_is_help=True, help="Contract tooling")
app.add_typer(contract_app, name="contract")
console = Console()

SwarmOpt = typer.Option(None, "--swarm", help="Swarm name (default: the enclosing project's)")


def _swarm(explicit: str | None) -> str:
    try:
        return resolve_swarm(explicit)
    except NoProjectError as e:
        console.print(f"[red]✗[/red] {e}")
        raise typer.Exit(1) from None


@app.callback()
def _version_callback() -> None:
    """Relay Agentic Framework CLI."""


# ── contract tooling ──────────────────────────────────────────────────────────

@contract_app.command("gen")
def contract_gen() -> None:
    """Regenerate contract/schema/*.json and docs/PROTOCOL.md from the contract."""
    contract = load_contract()
    paths = write_artifacts(contract)
    console.print(f"[green]✓[/green] contract {contract.contract_hash[:12]} — {len(paths)} artifacts written")


@contract_app.command("show")
def contract_show() -> None:
    """Summarize the loaded contract."""
    c = load_contract()
    console.print(f"version {c.version}, hash [bold]{c.contract_hash}[/bold]")
    console.print(f"{len(c.message_types)} message types, {len(c.edges)} edges, planes: {', '.join(c.planes)}")


# ── project initialization (also invoked automatically by `relay up`) ────────

def _initialize(project: Path, swarm: str, test_command: str) -> None:
    from relay.cli.profiles import write_profiles

    if sp.run(["git", "rev-parse", "--git-dir"], cwd=project, capture_output=True).returncode != 0:
        sp.run(["git", "init", "-q", "-b", "main"], cwd=project, check=True)
        console.print("[green]✓[/green] git repository initialized")
    gitignore = project / ".gitignore"
    marker = ".relay/"
    if not gitignore.exists() or marker not in gitignore.read_text():
        with gitignore.open("a") as f:
            f.write(f"\n# relay swarm runtime state\n{marker}\n")
        console.print(f"[green]✓[/green] added {marker} to .gitignore")
    if sp.run(["git", "rev-parse", "HEAD"], cwd=project, capture_output=True).returncode != 0:
        sp.run(["git", "add", "-A"], cwd=project, check=True)
        sp.run(["git", "commit", "-qm", "Initial commit (relay init)"], cwd=project, check=True)
        console.print("[green]✓[/green] initial commit created")

    profiles = write_profiles(project, swarm)
    console.print(f"[green]✓[/green] {len(profiles)} permission profiles → {profiles[0].parent}")

    gates_src = Path(__file__).resolve().parents[3] / "policies" / "gates.yaml"
    gates_dst = project / ".relay" / "gates.yaml"
    if gates_src.exists() and not gates_dst.exists():
        gates_dst.parent.mkdir(parents=True, exist_ok=True)
        gates_dst.write_text(gates_src.read_text())
        console.print(f"[green]✓[/green] gate policy → {gates_dst}")

    config = project / "relay.toml"
    if config.exists():
        return
    config.write_text(
        "# Relay swarm configuration for this project\n"
        f"# generated by relay {__version__}\n\n"
        "[swarm]\n"
        f'name = "{swarm}"\n\n'
        "[commands]\n"
        f'acceptance_test = "{test_command}"\n'
        '# suite = "uv run pytest -q"\n\n'
        "[roles.interpreter]\n"
        'runner = "claude"\nmodel = "opus"\n\n'
        "[roles.analyst]\n"
        'runner = "claude"\n\n'
        "[roles.specifier]\n"
        'runner = "claude"\n\n'
        "[roles.builder]\n"
        'runner = "claude"\n'
    )
    console.print(f"[green]✓[/green] wrote {config}")


@app.command()
def init(
    folder: Path = typer.Argument(Path("."), help="Project directory"),
    swarm: str = SwarmOpt,
    test_command: str = typer.Option(
        "uv run pytest -q {test_paths}", "--test-command",
        help="How the toolgate runs acceptance tests (use {test_paths})",
    ),
) -> None:
    """Prepare a project without starting it (relay up does this automatically)."""
    project = folder.expanduser().resolve()
    if not project.is_dir():
        console.print(f"[red]✗[/red] not a directory: {project}")
        raise typer.Exit(1)
    _initialize(project, swarm or project.name, test_command)


# ── runtime ───────────────────────────────────────────────────────────────────

@app.command()
def up(
    folder: Path = typer.Argument(Path("."), help="Project directory"),
    swarm: str = SwarmOpt,
    roles: str = typer.Option("", "--roles", help="Comma-separated subset (default: all Phase-1 roles)"),
    tmux: bool = typer.Option(False, "--tmux", help="Open a tmux session: watch + per-role tails"),
) -> None:
    """Start the swarm for a project (initializing it on first run)."""
    from relay.cli import procs, redisctl

    project = folder.expanduser().resolve()
    if not project.is_dir():
        console.print(f"[red]✗[/red] not a directory: {project}")
        raise typer.Exit(1)
    if not (project / "relay.toml").exists():
        _initialize(project, swarm or project.name, "uv run pytest -q {test_paths}")
    name = swarm or swarm_name(project)

    from relay.bus import groups as groups_mod
    from relay.bus.keys import group_name, ledger_key
    from relay.cli.profiles import write_profiles

    console.print(f"[green]✓[/green] {redisctl.ensure_running(procs.state_root())}")
    write_profiles(project, name)  # keep permission profiles + hooks current
    for role in ("interpreter", "owner"):  # interpreter mail queues even before chat opens
        groups_mod.ensure_group(get_client(), ledger_key(name), group_name(role))
    selected = [r.strip() for r in roles.split(",") if r.strip()]
    if not selected:
        from relay.coordinator.policy import Policy
        from relay.workers.run import resolve_policy_path

        selected = list(procs.PHASE1_ROLES)
        policy_path = resolve_policy_path(project)
        if policy_path is not None:
            policy = Policy.load(policy_path)
            for spec in (*policy.per_behaviour, *policy.per_story, *policy.per_iteration):
                if spec.role not in selected:
                    selected.append(spec.role)
    for role in selected:
        pid = procs.start_worker(name, role, project)
        console.print(f"[green]✓[/green] {role} (pid {pid})")
    console.print(f"\nswarm '[bold]{name}[/bold]' is up — next, in this folder:")
    console.print("  relay chat     (terminal 1 — talk to the swarm)")
    console.print("  relay watch    (terminal 2 — live board)")
    if tmux:
        _open_tmux(name, selected)


def _open_tmux(name: str, roles: list[str]) -> None:
    import shutil as _shutil

    if _shutil.which("tmux") is None:
        console.print("[yellow]•[/yellow] tmux not installed — skipping --tmux")
        return
    session = f"relay-{name}"
    sp.run(["tmux", "kill-session", "-t", session], capture_output=True)
    sp.run(["tmux", "new-session", "-d", "-s", session, "-n", "watch",
            f"relay watch --swarm {name}"], check=True)
    sp.run(["tmux", "set-option", "-t", session, "mouse", "on"], capture_output=True)
    for role in roles:
        sp.run(["tmux", "new-window", "-t", session, "-n", role,
                f"relay tail {role} --swarm {name}"], check=True)
    sp.run(["tmux", "select-window", "-t", f"{session}:watch"], capture_output=True)
    console.print(f"[green]✓[/green] tmux session ready (mouse on):  tmux attach -t {session}")


@app.command()
def down(swarm: str = SwarmOpt) -> None:
    """Stop the enclosing project's swarm (the ledger keeps everything)."""
    from relay.cli import procs

    name = _swarm(swarm)
    stopped = False
    for role in list(procs.running_roles(name)) or list(procs.PHASE1_ROLES):
        if procs.stop_worker(name, role):
            console.print(f"[green]✓[/green] {role} stopped")
            stopped = True
    if stopped:
        console.print(f"swarm '{name}' is down — `relay up` resumes exactly here")


NATIVE_SESSION_SUFFIX = """

== Session mode ==
You are the Interpreter, running as THIS Claude Code session. The human
talking to you here is the Owner. Speak to them directly — that is your
voice. Everything for the Analyst or the Coordinator goes through relay-send
on the bus; your terminal text is not work product for them.

Relay mail (analyst questions, checkpoints, escalations) reaches you
automatically: it is injected when you finish a turn and alongside whatever
the Owner types. When you have just dispatched work downstream and expect a
reply (e.g. after work.analysis_requested), do not end your turn in silence —
run `relay-inbox --swarm {swarm} --wait 240` to wait for the reply, then
brief the Owner on what arrived. Check `relay-inbox --swarm {swarm}` at the
start of the conversation for anything already waiting.

The Owner's words are recorded on the ledger automatically — never re-post
them. Mint ids with `relay-id q` / `relay-id gate`. Never leave the Owner
without a response.
"""


@app.command()
def chat(
    swarm: str = SwarmOpt,
    new: bool = typer.Option(False, "--new", help="Start a fresh conversation instead of continuing"),
) -> None:
    """Open the Interpreter: a native Claude Code session wired to the swarm."""
    import os
    import tomllib

    from relay.bus import groups as groups_mod
    from relay.bus.keys import group_name, ledger_key
    from relay.cli import procs
    from relay.cli.context import find_project
    from relay.cli.profiles import settings_path, write_profiles

    project = find_project()
    name = _swarm(swarm)

    # mail must queue even while no session is open
    client = get_client()
    for role in ("interpreter", "owner"):
        groups_mod.ensure_group(client, ledger_key(name), group_name(role))
    write_profiles(project, name)  # keep hooks/permissions current

    config = tomllib.loads((project / "relay.toml").read_text())
    interp_cfg = (config.get("roles") or {}).get("interpreter") or {}
    playbook = (Path(__file__).resolve().parents[3] / "roles" / "interpreter.md").read_text()
    system_prompt = playbook + NATIVE_SESSION_SUFFIX.format(swarm=name)

    marker = procs.state_root() / name / "interpreter" / "native-session"
    marker.parent.mkdir(parents=True, exist_ok=True)
    cmd = ["claude",
           "--dangerously-skip-permissions",
           "--append-system-prompt", system_prompt,
           # the settings file still matters: it carries the relay-inbox hooks
           "--settings", str(settings_path(project, "interpreter")),
           "--model", str(interp_cfg.get("model") or "opus")]
    if marker.exists() and not new:
        cmd.append("--continue")
        kickoff = None
    else:
        marker.write_text("started")
        kickoff = ("Introduce yourself to the Owner in two sentences, check "
                   f"`relay-inbox --swarm {name}` for anything already waiting, "
                   "and ask for their problem if there is none.")
    if kickoff:
        cmd.append(kickoff)
    os.chdir(project)
    os.execvp("claude", cmd)


@app.command()
def watch(swarm: str = SwarmOpt) -> None:
    """Live board: assistant liveness, behaviour states, event feed."""
    from relay.cli.watch import watch as watch_loop

    try:
        watch_loop(_swarm(swarm))
    except KeyboardInterrupt:
        pass


@app.command()
def tail(
    role: str = typer.Argument(..., help="Assistant role to follow"),
    swarm: str = SwarmOpt,
) -> None:
    """Follow one assistant's worker log."""
    import time as _time

    from relay.cli import procs

    log = procs.logfile(_swarm(swarm), role)
    console.print(f"[dim]{log}[/dim]")
    with log.open() as f:
        try:
            while True:
                line = f.readline()
                if line:
                    console.print(line.rstrip())
                else:
                    _time.sleep(0.5)
        except KeyboardInterrupt:
            pass


@app.command("acl")
def acl_gen(
    swarm: str = SwarmOpt,
    out: Path = typer.Option(None, "--out", help="Write the ACL script here (default: stdout)"),
) -> None:
    """Generate per-role Redis ACL provisioning commands for a multi-machine hub.

    One user per role, scoped to this swarm's keys, no admin commands — a
    compromised builder credential cannot read another swarm or reconfigure
    the hub. Run the output through redis-cli ON THE HUB, then distribute
    each credential to its host via REDIS_USERNAME/REDIS_PASSWORD.
    """
    import secrets

    name = _swarm(swarm)
    roles = ["coordinator", "toolgate", "interpreter", "analyst", "specifier",
             "builder", "reviewer", "qa", "security", "sentinel", "owner"]
    commands = ("+xadd +xreadgroup +xack +xautoclaim +xpending +xrange +xrevrange "
                "+xlen +xgroup +hget +hset +get +set +del +incr +scan +ping "
                "+script +evalsha +eval +info +config|get")
    lines = [f"# Redis ACLs for swarm '{name}' — run on the hub via redis-cli, then",
             f"# `ACL SAVE`. Rotate by re-running; distribute via env, never git.",
             ""]
    for role in roles:
        password = secrets.token_urlsafe(24)
        lines.append(
            f"ACL SETUSER relay-{name}-{role} on >{password} "
            f"~relay:{name}:* {commands}"
        )
        lines.append(f"#   {role}@host: export REDIS_USERNAME=relay-{name}-{role} "
                     f"REDIS_PASSWORD={password}")
    text = "\n".join(lines) + "\n"
    if out:
        out.write_text(text)
        out.chmod(0o600)
        console.print(f"[green]✓[/green] {out} (0600) — apply on the hub, then delete")
    else:
        print(text)


@app.command()
def pause(
    role: str = typer.Argument(..., help="Assistant role to pause"),
    swarm: str = SwarmOpt,
    reason: str = typer.Option("operator pause", "--reason"),
) -> None:
    """Pause a role's work intake (its mail waits in the PEL; nothing is lost)."""
    from relay.bus.publisher import Publisher

    publisher = Publisher(get_client(), ContractValidator(load_contract()), _swarm(swarm))
    publisher.send("coordinator", role, "control.pause", {"role": role, "reason": reason})
    console.print(f"[yellow]•[/yellow] {role} paused — resume with: relay resume {role}")


@app.command()
def resume(
    role: str = typer.Argument(..., help="Assistant role to resume"),
    swarm: str = SwarmOpt,
) -> None:
    """Resume a paused role; parked work is processed immediately."""
    from relay.bus.publisher import Publisher

    publisher = Publisher(get_client(), ContractValidator(load_contract()), _swarm(swarm))
    publisher.send("coordinator", role, "control.resume", {"role": role})
    console.print(f"[green]✓[/green] {role} resumed")


# ── observability / audit ─────────────────────────────────────────────────────

@app.command()
def status(swarm: str = SwarmOpt) -> None:
    """Ledger depth, DLQ depth, live presence."""
    name = _swarm(swarm)
    client = get_client()
    entries = client.xlen(ledger_key(name))
    dead = dlq_mod.dlq_depth(client, name)
    console.print(f"swarm '{name}'   ledger: {entries} entries   "
                  f"dlq: {'[red]' if dead else ''}{dead}{'[/red]' if dead else ''}")
    live = sorted(str(k) for k in client.scan_iter(match=presence_key(name, "*", "*")))
    if live:
        console.print("live workers:")
        for key in live:
            console.print(f"  • {key.rsplit(':', 1)[-1]}")
    else:
        console.print("live workers: none")


@app.command()
def audit(swarm: str = SwarmOpt) -> None:
    """Re-validate the whole ledger against the contract. Exit 1 on findings."""
    name = _swarm(swarm)
    report = audit_ledger(get_client(), ContractValidator(load_contract()), name)
    if report.ok:
        console.print(f"[green]✓[/green] {report.entries} entries, no findings")
        raise typer.Exit(0)
    table = Table(title=f"Audit findings — swarm '{name}' ({report.entries} entries)")
    table.add_column("seq")
    table.add_column("rule")
    table.add_column("detail")
    for f in report.findings:
        table.add_row(str(f.seq), f.rule, f.detail)
    console.print(table)
    raise typer.Exit(1)


@app.command()
def export(
    out: Path = typer.Option(..., "--out", help="Output JSONL path"),
    swarm: str = SwarmOpt,
) -> None:
    """Export the ledger as JSONL (fixtures, backups, incident capture)."""
    name = _swarm(swarm)
    count = export_jsonl(get_client(), name, out)
    console.print(f"[green]✓[/green] {count} entries → {out}")


@app.command()
def doctor(swarm: str = SwarmOpt) -> None:
    """Preflight checks: Redis reachable, AOF on, ledger audit clean."""
    name = _swarm(swarm)
    failures = 0
    try:
        client = get_client()
        client.ping()
        console.print("[green]✓[/green] redis reachable")
    except Exception as e:  # noqa: BLE001 — every failure is a finding here
        console.print(f"[red]✗[/red] redis unreachable: {e}")
        raise typer.Exit(1) from None

    appendonly = client.config_get("appendonly").get("appendonly")
    if appendonly == "yes":
        console.print("[green]✓[/green] AOF persistence on")
    else:
        console.print("[red]✗[/red] AOF is off — losing the ledger tail on power loss is a correctness bug")
        failures += 1

    report = audit_ledger(client, ContractValidator(load_contract()), name)
    if report.ok:
        console.print(f"[green]✓[/green] ledger audit clean ({report.entries} entries)")
    else:
        console.print(f"[red]✗[/red] ledger audit: {len(report.findings)} findings (run `relay audit`)")
        failures += 1

    raise typer.Exit(1 if failures else 0)


if __name__ == "__main__":
    app()
