"""The `relay` CLI.

Project-centric like git: `relay up <folder>` starts (auto-initializing on
first run); every other command finds the project by walking up from the
current directory. --swarm remains as an explicit override everywhere.
"""

from __future__ import annotations

import json
import subprocess as sp
from pathlib import Path

import typer
from rich.console import Console
from rich.table import Table

from relay import __version__
from relay.bus import dlq as dlq_mod
from relay.bus.client import get_client
from relay.bus.keys import ledger_key, presence_key
from relay.cli.context import NoProjectError, resolve_swarm, swarm_name
from relay.contract import ContractValidator, load_contract
from relay.contract.codegen import write_artifacts
from relay.ledger.audit import audit_ledger
from relay.ledger.export import export_jsonl

app = typer.Typer(no_args_is_help=True, help="Relay Agentic Framework")
contract_app = typer.Typer(no_args_is_help=True, help="Contract tooling")
app.add_typer(contract_app, name="contract")
# highlight=False: no auto-colorized digits/strings — output stays grep-able
# and identical in terminals, pipes, and tests; explicit markup still renders
console = Console(highlight=False)

SwarmOpt = typer.Option(None, "--swarm", help="Swarm name (default: the enclosing project's)")


def _swarm(explicit: str | None) -> str:
    try:
        return resolve_swarm(explicit)
    except NoProjectError as e:
        console.print(f"[red]✗[/red] {e}")
        raise typer.Exit(1) from None


@app.callback()
def _version_callback() -> None:
    """Relay Agentic Framework CLI."""


# ── contract tooling ──────────────────────────────────────────────────────────

@contract_app.command("gen")
def contract_gen() -> None:
    """Regenerate contract/schema/*.json and docs/PROTOCOL.md from the contract."""
    contract = load_contract()
    paths = write_artifacts(contract)
    console.print(f"[green]✓[/green] contract {contract.contract_hash[:12]} — {len(paths)} artifacts written")


@contract_app.command("show")
def contract_show() -> None:
    """Summarize the loaded contract."""
    c = load_contract()
    console.print(f"version {c.version}, hash [bold]{c.contract_hash}[/bold]")
    console.print(f"{len(c.message_types)} message types, {len(c.edges)} edges, planes: {', '.join(c.planes)}")


# ── project initialization (also invoked automatically by `relay up`) ────────

def _initialize(project: Path, swarm: str, test_command: str) -> None:
    from relay.cli.profiles import write_profiles

    if sp.run(["git", "rev-parse", "--git-dir"], cwd=project, capture_output=True).returncode != 0:
        sp.run(["git", "init", "-q", "-b", "main"], cwd=project, check=True)
        console.print("[green]✓[/green] git repository initialized")
    gitignore = project / ".gitignore"
    marker = ".relay/"
    if not gitignore.exists() or marker not in gitignore.read_text():
        with gitignore.open("a") as f:
            f.write(f"\n# relay swarm runtime state\n{marker}\n")
        console.print(f"[green]✓[/green] added {marker} to .gitignore")
    if sp.run(["git", "rev-parse", "HEAD"], cwd=project, capture_output=True).returncode != 0:
        sp.run(["git", "add", "-A"], cwd=project, check=True)
        sp.run(["git", "commit", "-qm", "Initial commit (relay init)"], cwd=project, check=True)
        console.print("[green]✓[/green] initial commit created")

    profiles = write_profiles(project, swarm)
    console.print(f"[green]✓[/green] {len(profiles)} permission profiles → {profiles[0].parent}")

    gates_src = Path(__file__).resolve().parents[3] / "policies" / "gates.yaml"
    gates_dst = project / ".relay" / "gates.yaml"
    if gates_src.exists() and not gates_dst.exists():
        gates_dst.parent.mkdir(parents=True, exist_ok=True)
        gates_dst.write_text(gates_src.read_text())
        console.print(f"[green]✓[/green] gate policy → {gates_dst}")

    from relay.cli.context import has_config

    if has_config(project):
        return
    config = project / ".relay" / "relay.toml"
    config.parent.mkdir(parents=True, exist_ok=True)
    config.write_text(
        "# Relay swarm configuration for this project\n"
        f"# generated by relay {__version__}\n\n"
        "[swarm]\n"
        f'name = "{swarm}"\n\n'
        "[commands]\n"
        f'acceptance_test = "{test_command}"\n'
        '# suite = "uv run pytest -q"\n\n'
        "[ui]\n"
        'terminal = "iterm"   # window app for `relay up --windows`: iterm | terminal\n\n'
        "# every role's model is EXPLICIT — an unset model must never fall back\n"
        "# to your personal Claude default (that once ran a swarm on the priciest tier)\n"
        "#\n"
        "# effort caps the agentic loop (low|medium|high|xhigh|max). Loop count is\n"
        "# what makes a turn expensive: every loop re-sends the whole context.\n"
        "# max_budget_usd is a HARD per-turn ceiling — the turn stops and the\n"
        "# worker fails loudly rather than spending whatever it takes.\n"
        "[roles.interpreter]\n"
        'runner = "claude"\nmodel = "opus"\neffort = "medium"\n\n'
        "[roles.analyst]\n"
        'runner = "claude"\nmodel = "sonnet"\neffort = "medium"\nmax_budget_usd = 2.5\n\n'
        "[roles.specifier]\n"
        'runner = "claude"\nmodel = "sonnet"\neffort = "medium"\nmax_budget_usd = 2.5\n\n'
        "[roles.builder]\n"
        'runner = "claude"\nmodel = "sonnet"\neffort = "high"\nmax_budget_usd = 3.0\n\n'
        "[roles.reviewer]\n"
        'model = "sonnet"\neffort = "medium"\nmax_budget_usd = 1.5\n\n'
        "[roles.qa]\n"
        'model = "sonnet"\neffort = "medium"\nmax_budget_usd = 1.5\n\n'
        "[roles.security]\n"
        'model = "sonnet"\neffort = "medium"\nmax_budget_usd = 1.5\n'
    )
    console.print(f"[green]✓[/green] wrote {config}")


@app.command()
def init(
    folder: Path = typer.Argument(Path("."), help="Project directory"),
    swarm: str = SwarmOpt,
    test_command: str = typer.Option(
        "uv run pytest -q {test_paths}", "--test-command",
        help="How the toolgate runs acceptance tests (use {test_paths})",
    ),
) -> None:
    """Prepare a project without starting it (relay up does this automatically)."""
    project = folder.expanduser().resolve()
    if not project.is_dir():
        console.print(f"[red]✗[/red] not a directory: {project}")
        raise typer.Exit(1)
    _initialize(project, swarm or project.name, test_command)


# ── runtime ───────────────────────────────────────────────────────────────────

@app.command()
def up(
    folder: Path = typer.Argument(Path("."), help="Project directory"),
    swarm: str = SwarmOpt,
    roles: str = typer.Option("", "--roles", help="Comma-separated subset (default: all Phase-1 roles)"),
    tmux: bool = typer.Option(False, "--tmux", help="Open a tmux session: watch + per-role tails"),
    windows: bool = typer.Option(False, "--windows",
                                 help="Open one Terminal window per assistant (live activity) + watch"),
) -> None:
    """Start the swarm for a project (initializing it on first run)."""
    from relay.cli import procs, redisctl

    project = folder.expanduser().resolve()
    if not project.is_dir():
        console.print(f"[red]✗[/red] not a directory: {project}")
        raise typer.Exit(1)
    from relay.cli.context import has_config

    legacy_config = project / "relay.toml"
    if legacy_config.is_file() and not (project / ".relay" / "relay.toml").exists():
        (project / ".relay").mkdir(exist_ok=True)
        legacy_config.rename(project / ".relay" / "relay.toml")
        console.print("[green]✓[/green] moved relay.toml → .relay/relay.toml (root stays clean)")
    if not has_config(project):
        _initialize(project, swarm or project.name, "uv run pytest -q {test_paths}")
    name = swarm or swarm_name(project)

    from relay.bus import groups as groups_mod
    from relay.bus.keys import group_name, ledger_key
    from relay.cli.profiles import write_profiles

    console.print(f"[green]✓[/green] {redisctl.ensure_running(procs.state_root())}")
    if not _claim_swarm(name, project):
        raise typer.Exit(1)
    write_profiles(project, name)  # keep permission profiles + hooks current
    for role in ("interpreter", "owner"):  # interpreter mail queues even before chat opens
        groups_mod.ensure_group(get_client(), ledger_key(name), group_name(role))
    selected = [r.strip() for r in roles.split(",") if r.strip()]
    if not selected:
        from relay.coordinator.policy import Policy
        from relay.workers.run import resolve_policy_path

        selected = list(procs.PHASE1_ROLES)
        policy_path = resolve_policy_path(project)
        if policy_path is not None:
            policy = Policy.load(policy_path)
            for spec in (*policy.per_behaviour, *policy.per_story, *policy.per_iteration):
                if spec.role not in selected:
                    selected.append(spec.role)
    for role in selected:
        pid = procs.start_worker(name, role, project)
        console.print(f"[green]✓[/green] {role} (pid {pid})")
    console.print(f"\nswarm '[bold]{name}[/bold]' is up — next, in this folder:")
    console.print("  relay chat     (terminal 1 — talk to the swarm)")
    console.print("  relay watch    (terminal 2 — live board)")
    if tmux:
        _open_tmux(name, selected)
    if windows:
        import tomllib

        from relay.cli.context import config_path

        ui_cfg = tomllib.loads(config_path(project).read_text()).get("ui") or {}
        _open_windows(name, selected, terminal=str(ui_cfg.get("terminal", "iterm")))


def _claim_swarm(name: str, project: Path) -> bool:
    """Two folders with the same basename must not share a ledger: a swarm
    name belongs to exactly one project directory."""
    from relay.bus.keys import project_key

    client = get_client()
    raw_owner = client.get(project_key(name))
    owner = raw_owner.decode() if isinstance(raw_owner, bytes) else raw_owner
    if owner and str(owner) != str(project):
        console.print(
            f"[red]✗[/red] swarm '{name}' already belongs to {owner}.\n"
            f"  Give this project its own name:  relay up . --swarm {name}-2\n"
            f"  (or set it permanently under [swarm] name in relay.toml)"
        )
        return False
    client.set(project_key(name), str(project))
    return True


def _open_windows(name: str, roles: list[str], terminal: str = "iterm") -> None:
    """One read-only viewer window per assistant + one mission-control watch.

    Viewers only: they follow logs and the stream, deliver nothing, and can be
    closed at any time without affecting the swarm. The terminal app comes
    from [ui] terminal in relay.toml — iTerm by default.
    """
    import platform

    import shutil as _shutil

    if platform.system() != "Darwin":
        console.print("[yellow]•[/yellow] --windows is macOS-only — use --tmux here")
        return
    # iTerm runs the command DIRECTLY (no shell, bare launchd PATH), so use the
    # absolute relay path and wrap in a login shell for the user's environment
    relay_bin = _shutil.which("relay") or "relay"
    commands = [f"{relay_bin} watch --swarm {name}"] + [
        f"{relay_bin} tail {r} --swarm {name}" for r in roles
    ]

    def _iterm(command: str) -> bool:
        shell_command = f"/bin/zsh -lc '{command}'"
        script = (f'tell application "iTerm"\n'
                  f'  create window with default profile command "{shell_command}"\n'
                  f'end tell')
        return sp.run(["osascript", "-e", script], capture_output=True).returncode == 0

    def _terminal_app(command: str) -> bool:
        return sp.run(["osascript", "-e",
                       f'tell application "Terminal" to do script "{command}"'],
                      capture_output=True).returncode == 0

    open_one = _iterm if terminal.lower() in ("iterm", "iterm2") else _terminal_app
    app_name = "iTerm" if open_one is _iterm else "Terminal"
    opened = 0
    for command in commands:
        if not open_one(command):
            if open_one is _iterm:  # iTerm missing/unscriptable → fall back once, loudly
                console.print("[yellow]•[/yellow] iTerm not reachable — falling back to Terminal.app "
                              '(set [ui] terminal = "terminal" in relay.toml to silence this)')
                open_one, app_name = _terminal_app, "Terminal"
                if open_one(command):
                    opened += 1
                continue
        else:
            opened += 1
    sp.run(["osascript", "-e", f'tell application "{app_name}" to activate'], capture_output=True)
    console.print(f"[green]✓[/green] {opened} {app_name} windows opened (read-only viewers)")


def _open_tmux(name: str, roles: list[str]) -> None:
    import shutil as _shutil

    if _shutil.which("tmux") is None:
        console.print("[yellow]•[/yellow] tmux not installed — skipping --tmux")
        return
    session = f"relay-{name}"
    sp.run(["tmux", "kill-session", "-t", session], capture_output=True)
    sp.run(["tmux", "new-session", "-d", "-s", session, "-n", "watch",
            f"relay watch --swarm {name}"], check=True)
    sp.run(["tmux", "set-option", "-t", session, "mouse", "on"], capture_output=True)
    for role in roles:
        sp.run(["tmux", "new-window", "-t", session, "-n", role,
                f"relay tail {role} --swarm {name}"], check=True)
    sp.run(["tmux", "select-window", "-t", f"{session}:watch"], capture_output=True)
    console.print(f"[green]✓[/green] tmux session ready (mouse on):  tmux attach -t {session}")


@app.command()
def down(swarm: str = SwarmOpt) -> None:
    """Stop the enclosing project's swarm (the ledger keeps everything)."""
    from relay.cli import procs

    name = _swarm(swarm)
    stopped = False
    for role in list(procs.running_roles(name)) or list(procs.PHASE1_ROLES):
        if procs.stop_worker(name, role):
            console.print(f"[green]✓[/green] {role} stopped")
            stopped = True
    strays = procs.reap_swarm(name)  # zombies with no pidfile (deleted state dirs)
    if strays:
        console.print(f"[yellow]•[/yellow] reaped {len(strays)} untracked worker(s): "
                      f"{', '.join(map(str, strays))}")
    if stopped or strays:
        console.print(f"swarm '{name}' is down — `relay up` resumes exactly here")


NATIVE_SESSION_SUFFIX = """

== Session mode ==
You are the Interpreter, running as THIS Claude Code session. The human
talking to you here is the Owner. Speak to them directly — that is your
voice. Everything for the Analyst or the Coordinator goes through relay-send
on the bus; your terminal text is not work product for them.

Relay mail (analyst questions, checkpoints, escalations) reaches you
automatically: it is injected when you finish a turn and alongside whatever
the Owner types. `relay-inbox --swarm {swarm} --wait 240` blocks your whole
turn and the Owner cannot reach you while it runs — use it ONLY when BOTH
are true: you just dispatched work downstream (e.g. analysis.requested), AND
you already told the Owner you are waiting. Never use --wait while greeting,
answering, or whenever the Owner might be typing; the plain, instant
`relay-inbox --swarm {swarm}` is always safe.

The Owner's words are recorded on the ledger automatically — never re-post
them. Mint ids with `relay-id q` / `relay-id gate`. Never leave the Owner
without a response.
"""


@app.command()
def destroy(
    swarm: str = SwarmOpt,
    force: bool = typer.Option(False, "--force", help="Skip the confirmation prompt"),
) -> None:
    """Remove every trace of a swarm: workers, ledger, Redis keys, local state.

    The project folder itself is untouched — delete it yourself if you want
    the code gone too. After destroy, `relay up` starts from a blank slate
    and `relay chat` begins a brand-new conversation.
    """
    import shutil

    from relay.cli import procs, redisctl

    name = _swarm(swarm)
    if not force and not typer.confirm(
        f"Erase swarm '{name}' completely (ledger, history, sessions)? This cannot be undone."
    ):
        raise typer.Exit(0)

    roles = list(procs.running_roles(name).items())
    if roles:
        console.print(f"stopping {len(roles)} worker(s)…")
        for role, pid in roles:
            console.print(f"  · {role} (pid {pid}) — waiting up to 3s for a clean exit…", end="")
            procs.stop_worker(name, role, timeout_s=3.0)  # a doomed swarm needs no grace
            console.print(" [green]stopped[/green]")
    else:
        console.print("no tracked workers running")
    strays = procs.reap_swarm(name)
    if strays:
        console.print(f"  · reaped {len(strays)} untracked worker(s): {', '.join(map(str, strays))}")

    console.print("deleting Redis keys (ledger, groups, claims)…", end="")
    deleted = redisctl.wipe_swarm_keys(get_client(), name)
    console.print(f" [green]{deleted} deleted[/green]")

    state = procs.state_root() / name
    if state.exists():
        console.print(f"removing {state} (logs, sessions, chat marker)…", end="")
        shutil.rmtree(state)
        console.print(" [green]done[/green]")
    console.print(f"[bold green]✓[/bold green] swarm '{name}' is gone — `relay up` starts from nothing")


@app.command()
def chat(
    swarm: str = SwarmOpt,
    new: bool = typer.Option(False, "--new", help="Start a fresh conversation instead of continuing"),
) -> None:
    """Open the Interpreter: a native Claude Code session wired to the swarm."""
    import os
    import tomllib

    from relay.bus import groups as groups_mod
    from relay.bus.keys import group_name, ledger_key
    from relay.cli import procs
    from relay.cli.context import find_project
    from relay.cli.profiles import settings_path, write_profiles

    project = find_project()
    name = _swarm(swarm)

    # mail must queue even while no session is open
    client = get_client()
    for role in ("interpreter", "owner"):
        groups_mod.ensure_group(client, ledger_key(name), group_name(role))
    write_profiles(project, name)  # keep hooks/permissions current

    from relay.cli.context import config_path

    config = tomllib.loads(config_path(project).read_text())
    interp_cfg = (config.get("roles") or {}).get("interpreter") or {}
    playbook = (Path(__file__).resolve().parents[3] / "roles" / "interpreter.md").read_text()
    system_prompt = playbook + NATIVE_SESSION_SUFFIX.format(swarm=name)

    marker = procs.state_root() / name / "interpreter" / "native-session"
    marker.parent.mkdir(parents=True, exist_ok=True)
    cmd = ["claude",
           "--dangerously-skip-permissions",
           "--append-system-prompt", system_prompt,
           # the settings file still matters: it carries the relay-inbox hooks
           "--settings", str(settings_path(project, "interpreter")),
           "--model", str(interp_cfg.get("model") or "opus")]
    if marker.exists() and not new:
        cmd.append("--continue")
        kickoff = None
    else:
        marker.write_text("started")
        # leading '<' marks this as synthetic: the hook must NOT record it as
        # the owner's words, and the model must never block on --wait here
        kickoff = ("<relay-kickoff> Run `relay-inbox --swarm "
                   f"{name}` once (WITHOUT --wait — the Owner is about to type), "
                   "then introduce yourself in two sentences and ask for their "
                   "problem if none is pending.")
    if kickoff:
        cmd.append(kickoff)
    os.chdir(project)
    # execvpe, not execvp: the session's hooks and every relay-send the
    # Interpreter runs need the relay commands on PATH, and a login shell
    # does not read ~/.zshrc
    from relay.cli.entrypoints import env_with_entrypoints

    os.execvpe("claude", cmd, env_with_entrypoints())


@app.command()
def watch(
    swarm: str = SwarmOpt,
    events: bool = typer.Option(False, "--events",
                                help="Event log: every ledger event from the start, as a table"),
    tokens: bool = typer.Option(False, "--tokens",
                                help="Token burn: spend per role and per turn, as it happens"),
) -> None:
    """Live board: assistant liveness, behaviour states, event feed.

    With --events: the full audited history instead — timestamp, producer,
    type, work-item ref, payload — scrollback-friendly.

    With --tokens: what the swarm is spending, folded from the ledger as it
    lands — per role (with the model that actually billed, and how many turns
    started cold), the running rate, cache warmth, and the last turns as they
    complete. Same arithmetic as `relay costs`, live.

    All three views follow; Ctrl-C stops.
    """
    from relay.cli.watch import events_view, tokens_view
    from relay.cli.watch import watch as watch_loop

    if events and tokens:
        console.print("[red]✗[/red] --events and --tokens are different views: pick one")
        raise typer.Exit(1)
    try:
        if tokens:
            tokens_view(_swarm(swarm))
        elif events:
            events_view(_swarm(swarm))
        else:
            watch_loop(_swarm(swarm))
    except KeyboardInterrupt:
        pass


@app.command()
def tail(
    role: str = typer.Argument(..., help="Assistant role to follow"),
    swarm: str = SwarmOpt,
) -> None:
    """Follow one assistant's worker log."""
    import time as _time

    from relay.cli import procs

    log = procs.logfile(_swarm(swarm), role)
    console.print(f"[dim]{log}[/dim]")
    with log.open() as f:
        try:
            while True:
                line = f.readline()
                if line:
                    console.print(line.rstrip())
                else:
                    _time.sleep(0.5)
        except KeyboardInterrupt:
            pass


@app.command("acl")
def acl_gen(
    swarm: str = SwarmOpt,
    out: Path = typer.Option(None, "--out", help="Write the ACL script here (default: stdout)"),
) -> None:
    """Generate per-role Redis ACL provisioning commands for a multi-machine hub.

    One user per role, scoped to this swarm's keys, no admin commands — a
    compromised builder credential cannot read another swarm or reconfigure
    the hub. Run the output through redis-cli ON THE HUB, then distribute
    each credential to its host via REDIS_USERNAME/REDIS_PASSWORD.
    """
    import secrets

    name = _swarm(swarm)
    roles = ["coordinator", "toolgate", "interpreter", "analyst", "specifier",
             "builder", "reviewer", "qa", "security", "sentinel", "owner"]
    commands = ("+xadd +xreadgroup +xack +xautoclaim +xpending +xrange +xrevrange "
                "+xlen +xgroup +hget +hset +get +set +del +incr +scan +ping "
                "+script +evalsha +eval +info +config|get")
    lines = [f"# Redis ACLs for swarm '{name}' — run on the hub via redis-cli, then",
             f"# `ACL SAVE`. Rotate by re-running; distribute via env, never git.",
             ""]
    for role in roles:
        password = secrets.token_urlsafe(24)
        lines.append(
            f"ACL SETUSER relay-{name}-{role} on >{password} "
            f"~relay:{name}:* {commands}"
        )
        lines.append(f"#   {role}@host: export REDIS_USERNAME=relay-{name}-{role} "
                     f"REDIS_PASSWORD={password}")
    text = "\n".join(lines) + "\n"
    if out:
        out.write_text(text)
        out.chmod(0o600)
        console.print(f"[green]✓[/green] {out} (0600) — apply on the hub, then delete")
    else:
        print(text)


@app.command()
def pause(
    role: str = typer.Argument(..., help="Assistant role to pause"),
    swarm: str = SwarmOpt,
    reason: str = typer.Option("operator pause", "--reason"),
) -> None:
    """Pause a role's work intake (its mail waits in the PEL; nothing is lost)."""
    from relay.bus.publisher import Publisher

    publisher = Publisher(get_client(), ContractValidator(load_contract()), _swarm(swarm))
    publisher.send("coordinator", role, "pause.ordered", {"role": role, "reason": reason})
    console.print(f"[yellow]•[/yellow] {role} paused — resume with: relay resume {role}")


@app.command()
def resume(
    role: str = typer.Argument(..., help="Assistant role to resume"),
    swarm: str = SwarmOpt,
) -> None:
    """Resume a paused role; parked work is processed immediately."""
    from relay.bus.publisher import Publisher

    publisher = Publisher(get_client(), ContractValidator(load_contract()), _swarm(swarm))
    publisher.send("coordinator", role, "resume.ordered", {"role": role})
    console.print(f"[green]✓[/green] {role} resumed")


@app.command()
def costs(
    swarm: str = SwarmOpt,
    by_behaviour: bool = typer.Option(False, "--by-behaviour",
                                      help="Group by work item instead of by role"),
    transcripts: bool = typer.Option(False, "--transcripts",
                                     help="Read the Claude session files instead of the ledger"),
) -> None:
    """What the engagement cost, folded from the ledger.

    Every model turn publishes `usage.reported` against the work item it was
    serving, so this survives `relay destroy` and attributes honestly. Cache
    read against cache write is the number to watch: reads bill at a tenth,
    writes at 1.25x, so a run that keeps its sessions warm is far cheaper than
    its raw token count suggests.

    --transcripts falls back to the Claude session files (per-API-call detail,
    but attributed by guesswork and deleted with the project).
    """
    if not transcripts:
        _costs_from_ledger(_swarm(swarm), by_behaviour=by_behaviour)
        return

    from relay.cli.context import find_project
    from relay.cli.costs import analyze

    try:
        project = find_project()
    except NoProjectError as e:
        console.print(f"[red]✗[/red] {e}")
        raise typer.Exit(1) from None
    per_role, sessions = analyze(project)
    if not per_role:
        console.print("no session transcripts found for this project yet")
        raise typer.Exit(0)
    table = Table(title=f"token usage — {project.name} ({sessions} sessions)")
    for col in ("role", "api calls", "fresh in", "cache write", "cache read", "output"):
        table.add_column(col, justify="right" if col != "role" else "left")
    totals = {k: 0 for k in ("api_calls", "input_tokens", "cache_creation_input_tokens",
                             "cache_read_input_tokens", "output_tokens")}
    for role, u in sorted(per_role.items(),
                          key=lambda kv: -(kv[1]["cache_creation_input_tokens"]
                                           + kv[1]["cache_read_input_tokens"])):
        table.add_row(role, f"{u['api_calls']:,}", f"{u['input_tokens']:,}",
                      f"{u['cache_creation_input_tokens']:,}",
                      f"{u['cache_read_input_tokens']:,}", f"{u['output_tokens']:,}")
        for k in totals:
            totals[k] += u[k]
    table.add_row("[bold]total[/bold]", *(f"[bold]{totals[k]:,}[/bold]" for k in totals))
    console.print(table)


def _costs_from_ledger(swarm: str, *, by_behaviour: bool) -> None:
    from relay.ledger.usage import billed_input_equivalents, fold_usage

    report = fold_usage(get_client(), swarm)
    if report.empty:
        console.print("no model turns recorded on this ledger yet "
                      "(older swarms: try [bold]relay costs --transcripts[/bold])")
        raise typer.Exit(0)

    rows = report.by_behaviour if by_behaviour else report.by_role
    label = "work item" if by_behaviour else "role"
    table = Table(title=f"model spend — swarm {swarm} ({report.total['turns']} turns)")
    table.add_column(label, min_width=11)  # never abbreviate a role name
    for col in ("turns", "cold", "agent turns", "cache write", "cache read", "output", "cost"):
        table.add_column(col, justify="right")

    def add(name: str, row: dict[str, object], bold: bool = False) -> None:
        mark = (lambda s: f"[bold]{s}[/bold]") if bold else (lambda s: s)
        table.add_row(
            mark(name),
            mark(f"{row['turns']:,}"),
            mark(f"{row['fresh_sessions']:,}"),
            mark(f"{row['agent_turns']:,}"),
            mark(f"{row['cache_creation_input_tokens']:,}"),
            mark(f"{row['cache_read_input_tokens']:,}"),
            mark(f"{row['output_tokens']:,}"),
            mark(f"${row['cost_usd']:.2f}"),
        )

    for name, row in sorted(rows.items(), key=lambda kv: -float(kv[1]["cost_usd"])):
        add(name, row)
    add("total", report.total, bold=True)
    console.print(table)

    equivalents = billed_input_equivalents(report.total)
    written = report.total["cache_creation_input_tokens"]
    read = report.total["cache_read_input_tokens"]
    warmth = (read / (read + written)) if (read + written) else 0.0
    console.print(
        f"billed input equivalents: {equivalents:,.0f} tokens  ·  "
        f"cache warmth {warmth:.0%} (reads bill at 0.1x, writes at 1.25x)  ·  "
        f"{report.total['fresh_sessions']} of {report.total['turns']} turns started cold"
    )
    models = ", ".join(
        f"{m} ({r['turns']} turn{'s' if r['turns'] != 1 else ''}, ${r['cost_usd']:.2f})"
        for m, r in sorted(report.by_model.items(), key=lambda kv: -float(kv[1]["cost_usd"]))
    )
    console.print(f"models billed: {models}")


# ── observability / audit ─────────────────────────────────────────────────────

@app.command()
def status(swarm: str = SwarmOpt) -> None:
    """Ledger depth, DLQ depth, live presence."""
    name = _swarm(swarm)
    client = get_client()
    entries = client.xlen(ledger_key(name))
    dead = dlq_mod.dlq_depth(client, name)
    console.print(f"swarm '{name}'   ledger: {entries} entries   "
                  f"dlq: {'[red]' if dead else ''}{dead}{'[/red]' if dead else ''}")
    live = sorted(str(k) for k in client.scan_iter(match=presence_key(name, "*", "*")))
    if live:
        console.print("live workers:")
        for key in live:
            console.print(f"  • {key.rsplit(':', 1)[-1]}")
    else:
        console.print("live workers: none")


@app.command()
def audit(swarm: str = SwarmOpt) -> None:
    """Re-validate the whole ledger against the contract. Exit 1 on findings."""
    name = _swarm(swarm)
    report = audit_ledger(get_client(), ContractValidator(load_contract()), name)
    if report.ok:
        console.print(f"[green]✓[/green] {report.entries} entries, no findings")
        raise typer.Exit(0)
    table = Table(title=f"Audit findings — swarm '{name}' ({report.entries} entries)")
    table.add_column("seq")
    table.add_column("rule")
    table.add_column("detail")
    for f in report.findings:
        table.add_row(str(f.seq), f.rule, f.detail)
    console.print(table)
    raise typer.Exit(1)


@app.command()
def export(
    out: Path = typer.Option(..., "--out", help="Output JSONL path"),
    swarm: str = SwarmOpt,
) -> None:
    """Export the ledger as JSONL (fixtures, backups, incident capture)."""
    name = _swarm(swarm)
    count = export_jsonl(get_client(), name, out)
    console.print(f"[green]✓[/green] {count} entries → {out}")


@app.command()
def doctor(swarm: str = SwarmOpt) -> None:
    """Preflight checks: Redis reachable, AOF on, ledger audit clean."""
    name = _swarm(swarm)
    failures = 0
    try:
        client = get_client()
        client.ping()
        console.print("[green]✓[/green] redis reachable")
    except Exception as e:  # noqa: BLE001 — every failure is a finding here
        console.print(f"[red]✗[/red] redis unreachable: {e}")
        raise typer.Exit(1) from None

    appendonly = client.config_get("appendonly").get("appendonly")
    if appendonly == "yes":
        console.print("[green]✓[/green] AOF persistence on")
    else:
        console.print("[red]✗[/red] AOF is off — losing the ledger tail on power loss is a correctness bug")
        failures += 1

    report = audit_ledger(client, ContractValidator(load_contract()), name)
    if report.ok:
        console.print(f"[green]✓[/green] ledger audit clean ({report.entries} entries)")
    else:
        console.print(f"[red]✗[/red] ledger audit: {len(report.findings)} findings (run `relay audit`)")
        failures += 1

    raise typer.Exit(1 if failures else 0)


if __name__ == "__main__":
    app()
